### ISSUE TITLE
it shows only these for any exe

### ISSUE THREAD

**Issue by Mafhoom** [unipacker/unipacker#42]
I install it without any errors but now it shows these with test by any exe
Python39>unipacker
v1.0.3

Your options for today:

        [0]  New sample...

Enter the option ID: 0
Please enter the sample path (single file or directory): 1.exe
OPT Magic: 523
Wrong Optional Header Magic. Aborting...
Could not initialize 1.exe:
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\unipacker.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\unipacker\shell.py", line 738, in main
    Shell()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\unipacker\shell.py", line 82, in __init__
    self.shell_event.wait()
AttributeError: 'Shell' object has no attribute 'shell_event'

anybody can help?

**Comment by vfsrfs** [comment]
Thank you for the issue. You are trying to unpack a sample, which is a 64bit binary (Optional Header Magic Value 523 = 0x20B = PE32+ [https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-image-only](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-image-only)). Unfortunately, 64-bit binaries are not supported right now, only 32bit binaries. Either way, feel free to share the sample, as it might be useful for us, when adding support for 64-bit binaries. Are you aware, which packer was used to pack that sample?

We should probably modify the message output to informing about the Optional Header Mismatch and replace it by a message stating that 64bit binaries are not supported yet. I don't know if the shell crash only occurs on Windows, as the Windows build is a bit problematic compared to the linux build, but we should improve the error handling to avoid the crash.

**Comment by Masrepus** [comment]
Without having looked into this in more detail yet, I think this isn't Windows specific but probably there is some error handling missing for 64bit binaries
