### ISSUE TITLE
Errors trying to run the command

### ISSUE THREAD

**Issue by kittyflip** [unipacker/unipacker#50]
Traceback (most recent call last):
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\Scripts\unipacker.exe\__main__.py", line 4, in <module>
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\lib\site-packages\unipacker\shell.py", line 13, in <module>
    from cmd2 import Cmd
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\lib\site-packages\cmd2\__init__.py", line 13, in <module>
    from .cmd2 import Cmd, Statement, EmptyStatement, categorize
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\lib\site-packages\cmd2\cmd2.py", line 48, in <module>
    from . import utils
  File "C:\Users\Source\AppData\Local\Programs\Python\Python310\lib\site-packages\cmd2\utils.py", line 73, in <module>
    default_values: collections.Iterable = ()):
AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by Masrepus** [comment]
Apparently the `collections.Iterable` class has been deprecated in Python 3.10, which one of our dependencies relies on. Thus unipacker doesn't support this Python version at the moment. We will investigate Python 3.10 support but can't provide a timeline for this unfortunately, so in the meantime the workaround is to use Python 3.9 or lower

**Comment by Boberttt** [comment]
Temp solution:
in unix open .local/lib/python3.11/site-packages/cmd2/utils.py
on line 95, change the collections.Mapping in "isinstance(default_values, collections.Mapping):" with collections.abc.Mapping
On line 73 change the collections.Iterable part to collections.abc.Iterable

**Comment by grepwood** [comment]
It's been a year and a half since.
To make matters worse, the last version of Python supported by unipacker (3.9) has lost active support a month before this issue was made.

This has been plenty amount of time to fix the issue. I'm going to make a PR because I can't wait for someone else to fix this.
